logitechmediaserver:
  container_name: "logitechmediaserver"
  image: davomat/logitechmediaserver
  ports:
    - 9000:9000
    - 9090:9090
    - 3483:3483
    - 3483/udp:3483/udp
    - 9005:9005
  volumes:
    - /home/public/Music:/home/public/Music
    - /home/public/Playlists:/home/public/Playlists
    - /var/lib/squeezeboxserver:/var/lib/squeezeboxserver
